on:
  push:
    branches:
      - master
      - main
      
# Secrets:
#   PYPIRC - pypi configuration file
      
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7
          
      - name: Install dependecies
        run: |
          pip install wheel~=0.34.2
          pip install twine
          pip install -r requirements.txt
          
      - name: Build
        run: python setup.py bdist_wheel
          
      - name: Publish
        run: |
          echo "${{ secrets.pypirc }}" > .pypirc
          python -m twine upload --config-file .pypirc -r pypitest dist/*
          
