on:
  push:
    branches:
      - master
      - main
      
  workflow_dispatch:
    inputs:
      bump:
        description: bump rule (major|minor|patch|tag|addon)
        default: tag
        required: false
        
      version:
        description: manual version
        default: ''
        required: false
        
      release:
        description: release type (local|global)
        default: local
        required: false
        
# Secrets:
#   PYPIRC - pypi configuration file
      
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Validate inputs  #TODO create an action for this
        env:
          BUMP: ${{ event.inputs.bump }}
          RELEASE: ${{ event.inputs.release }}
        run: |
          case $BUMP in
            major)
              ;;
            minor)
              ;;
            patch)
              ;;
            tag)
              ;;
            addon)
              ;;
            *)
              echo "invalid bump rule: $BUMP"
              exit 1
              ;;
          esac
          
          case $RELEASE in 
            local)
              ;;
            global)
              ;;
            *)
              echo invalid release type: $RELEASE
              exit 1
              ;;
              
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7
          
      - name: Install dependecies
        run: |
          pip install wheel~=0.34.2
          pip install twine
          pip install -r requirements.txt
          
      - name: Build
        run: python setup.py bdist_wheel
          
      - name: Publish
        run: |
          echo "${{ secrets.pypirc }}" > .pypirc
          python -m twine upload --config-file .pypirc -r pypitest dist/*
          
