on:
  push:
    branches:
      - master
      - main
      
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8

      - name: Build and publish
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install wheel~=0.34.2
          pip install twine
          pip install -r requirements.txt
          echo ${{ secrets.pypirc }} > .pypirc
          cat .pypirc
          python -m twine upload --config-file .pupirc -r pypitest dist/*
